name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]

    steps:
      - uses: actions/checkout@v2

      - name: Build(cmake)
        run: |
          pushd cola
          mkdir -p build
          pushd build
          cmake ..
          make
          popd
          popd

      - name: Run unit tests
        run: |
          pushd cola
          mkdir -p build_tests
          pushd build_tests
          cmake -DENABLE_TESTS=ON ..
          make
          ctest --output-on-failure
          popd
          popd

      - name: Build(make)
        run: |
          pushd cola
          ./autogen.sh
          popd

      - name: Build bindings(webassembly)
        run: |
          pushd cola/bindings/webassembly/libavoid-js/
          mkdir build
          pushd build
          python3 ../tools/generate.py
